### ISSUE TITLE
Possible issue with cutscene

### ISSUE THREAD

**Issue by waebbl** [BiGWorldProject/TDDz#13]
Hi,

there seems to be a possible issue with a cutscene in the Trollford caves in area DD9004. Usually the cutscene starts immediately after you enter the area and the troll is killing the adventure boy.

However, I had the autopause trigger "Enemy sighted" enabled, so the game pauses when entering the area, before the cutscene starts. When I then click to attack the troll, the group starts walking to the troll and attacks it almost the same time when the cutscene also starts. The result is, the troll get's attacked and doesn't attack the boy, so the cutscene never end. Space (pause) or Esc key didn't work, but the troll also doesn't die. The game runs in an infinite loop where my group attacks the undying troll and needs to be killed via a taskmanager or similar tool.

The behaviour is reproducible.
I'm running a mostly basic SandrahNPC big mod EET installation on linux (only the needed mods are installed, with very few additional mods). Weidu.log can be provided if you need it.

You can watch a recording of what's going on at
https://drive.google.com/file/d/1A3Ow3gAe2OXF25VnQr1Fx9I3NF7A2sVq/view?usp=sharing

Maybe there's a possibility, so this can not happen, by starting the troll with a neutral state and trigger to an enemy state only once the cutscene is finished, i.e. the boy has been killed, or some other means?

**Comment by ALIENQuake** [comment]
@waebbl Hey, during my test, when I enter this area, I don't see the troll at my Fog-of-War: https://i.imgur.com/Gm7jq0G.png
Did you do something to increase the party vision region?

**Comment by waebbl** [comment]
@ALIENQuake Thanks for your reply and testing. I know of nothing I have done to increase party vision. 

Your image looks like you are testing with a solo game. Watching my video again, I got the idea, it might be due to me having a party of six, which moves the front character further into the region and thus removes the fog-of-war up to the troll. Could this be the reason why the troll is immediately visible for me?

**Comment by ALIENQuake** [comment]
@waebbl Try this file, unzip into override: 
[DD9004.zip](https://github.com/InfinityMods/TDDz/files/5114524/DD9004.zip)

**Comment by waebbl** [comment]
I just tried removing all but my protagonist and got the situation as in https://imgur.com/NTgkw7J so the party size doesn't seem to be the issue.

I'm going to check your zip file.

**Comment by waebbl** [comment]
The patch works. It moved the troll far enough away, so it wasn't visible when the cutscene was running in about two handful tries. On a few occasions it didn't even become visible during the cutscene, as the guy moved up to the troll without the troll coming into sight.

**Comment by ALIENQuake** [comment]
Great, so let's add this tiny change 😃

**Comment by ALIENQuake** [comment]
Fixed by v1.3.1

**Comment by waebbl** [comment]
@ALIENQuake Thanks for your help!
