### ISSUE TITLE
Request: Use OlvynChuru's Class Spell Tool on the new spells to bypass the 50 spells per level limit.

### ISSUE THREAD

**Issue by Endarire** [BiGWorldProject/TDDz#14]
Greetings!

OlvynChuru recently released [this tool](https://forums.beamdog.com/discussion/80718/tool-adding-class-or-kit-specific-spells) to easily avoid the 50 spells per type (arcane/divine) per spell level.  Since this tool only works for EE games, my request is to use this tool and upload a new version that works with this tool for EE- and EET-specific installs.  (Conveniently, TDDz is EE-specific.)

Thankee!

**Comment by Endarire** [comment]
@ALIENQuake @RoxanneSHS @K4thos 
Greetings, repository contributors!

What say you to revamping TDDz with the aforementioned spell tool to reduce the chances of users reaching the 50 spells per type per spell level limit?

Thankee!

**Comment by RoxanneSHS** [comment]
THIS IS NONSENSE!!!!
Did you even look at TDDz or are you just repeating lies spread around elsewhere?
Tell me of a single spell in TDDz that falls under that category!!!!!
The few spells added by the mod are only used by enemy spellcasters via scripts.
"Big old mods do bad things....", go and tell your stupid propaganda to those who have no idea about the topic.
