### ISSUE TITLE
ARPO10.bcs

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/TDDz#2]
IF 
Global("tz_TDD_Complete","GLOBAL",1) 
THEN RESPONSE #100 
TriggerActivation("DOOR0153",TRUE)
END

This block should be deleted, it opens a door into a none existing area. That was the old transition in TDD to ToB which is no longer valid in TDDz.

**Comment by agb1** [comment]
Both of these blocks are not needed, correct?

Block 1:

IF
  Global("tz_TDD_Complete","GLOBAL",0)
THEN
  RESPONSE #100
    TriggerActivation("DOOR0153",FALSE)
END

Block 2:

IF
  Global("tz_TDD_Complete","GLOBAL",1)
THEN
  RESPONSE #100
    TriggerActivation("DOOR0153",TRUE)
END

**Comment by RoxanneSHS** [comment]
Block 1 is needed - unless you delete the travel trigger Door153 from the are file.
At the moment this trigger is there and removing block 1 would make it accessible - if you walk through the door you get CtD. (Block 2 opens it after the TDD quest and thus creates the same effect).
So either remove block 2 or remove the travel trigger.

**Comment by RoxanneSHS** [comment]
Edit
On second thought - removing the travel trigger may not be a real option since TDDz uses the original resource from TDD. You would need to override arp010.are with a version having the trigger removed.

**Comment by RoxanneSHS** [comment]
wrong button (close)

**Comment by agb1** [comment]
Thanks. I've changed the condition for the first block to True() and disabled the second block, with detailed comments in the baf file. Please close unless you see a problem with this solution.

**Comment by RoxanneSHS** [comment]
True() would block anything that may follow below unless you add Continue() as well. There is nothing below in the original bcs but there may be mod added stuff (Afaaq, Haiass, packmule and such add to area scripts to follow the PC).
