### ISSUE TITLE
TROLLFORD is broken (missed flags: droppable)

### ISSUE THREAD

**Issue by simeonkosnitsky** [BiGWorldProject/TDDz#7]
BiGWorldProject-TDDz-v1.2.5-0-g71ce503.zip

TDDz\_TROLLFORD\ItemsContract.2da

KEYKIDDY - Prison Key * required for finish quest

ZGORGET - Zhentarim Battle Gorget * obtained as reward

* all other found in boxes and can't be removed from inventory as result
SINKER - Sinker 
SKIMFLAM - Crimson Ember
KING - Winter King's Plate
DETHSTFZ - Hemolust
DUERGAXX - Rock Cleaver
GIANTGRC - Giant's Grace
POISONZZ - Poison Ivy

**Comment by RoxanneSHS** [comment]
Tried to correct it.
Sorry for the delay - Github did not send a notification?
