### ISSUE TITLE
Missing spell bams

### ISSUE THREAD

**Issue by RoxanneSHS** [BiGWorldProject/TDDz#8]
I noticed that the TDD install did not copies all BAM files from TDD.

The spells like Enbalm and Visions of Pain miss the spellbook icons.

See https://github.com/EE-Mod-Setup/EE-Mod-Setup/issues/4

**Comment by ALIENQuake** [comment]
@RoxanneSHS Does this issue still exist?

**Comment by RoxanneSHS** [comment]
Nothing has been done here. I checked my installation with NI and found the bams missing.
I have not encountered the issue in game but that may just be coincidence because I may not have picked those scrolls or whatever. I cannot say whether it has really an impact but I seem to remember that some player reported it to me a while ago.

Possible solution:
Add new line 93 into the tp2
COPY `~TDD/Bam~ ~override~`

Do this prior to other install stuff so more granular later updates can override this general copy. (Otherwise one needs to check every component and every spell). TDD is early in an install sequence and prior to any spell or item mods that may do other updates, so that is why I see no problem in such a simple solution.

**Comment by ALIENQuake** [comment]
Since I don't see a way how extra bam's could break something, mentioned change was added by a38e040.
