### ISSUE TITLE
Install order

### ISSUE THREAD

**Issue by Majber** [BiGWorldProject/TDDz#9]
What is exact install order to make it work?
 Is it:
1. Worldmap 10.2
2. Extended Animation
3. Copy only TDD folder from TDD 1.14 to Bg2 folder with  .exe file
4. Copy TDDz folder and setup and start Setup-TDDz   ?

**Comment by ALIENQuake** [comment]
@Majber 

1. Copy only TDD folder from TDD 1.14 to Bg2 folder with .exe file
1. Copy TDDz folder and setup and start Setup-TDDz ?
1. Worldmap

I don't know anything about Extended Animation but I guess you install it at the beginning. 

Please use community forum if you want to ask about install order etc
